drop table if exists member CASCADE ;

create table user
(
 id bigint generated by default as identity,
 name varchar(255),
 password varchar(255),
 email varchar(255),
 primary key (id)
);

insert into user(name,password,email) values ('wonjae','aaa','wj.jeon@konai.com');

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

select * from user;