create Member kafkashop IDENTIFIED by 1234;

grant connect, resource, dba to kafkashop;

drop table if exists member CASCADE ;

ALTER Member SA SET PASSWORD '';

jdbc:h2:./kafkashop
jdbc:h2:tcp://localhost/./kafkashop

CREATE SEQUENCE member_id_seq START WITH 1 INCREMENT BY 1;
create table member
(
 id int generated by default as identity,
 name varchar(255),
 password varchar(255),
 email varchar(255),
 primary key (id)
);

insert into Member(name,password,email) values ('wonjae','aaa','wj.jeon@konai.com');

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

select * from Member;