create Member kafkashop IDENTIFIED by 1234;

grant connect, resource, dba to kafkashop;

drop table if exists member CASCADE ;

ALTER Member SA SET PASSWORD '';

jdbc:h2:./kafkashop
jdbc:h2:tcp://localhost/./kafkashop

CREATE SEQUENCE member_id_seq START WITH 1 INCREMENT BY 1;
create table member
(
 id int generated by default as identity,
 name varchar(255),
 password varchar(255),
 email varchar(255),
 primary key (id)
);

insert into Member(name,password,email) values ('wonjae','aaa','wj.jeon@konai.com');

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

select * from Member;


drop table board;
CREATE TABLE board (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255),
    content VARCHAR2(1000),
    created_at TIMESTAMP,
    writer_id NUMBER(19), -- 글쓴 회원의 ID
    writer_name VARCHAR2(255),
    FOREIGN KEY (writer_id) REFERENCES member (id) -- 외래키 설정
);